- name: activate beta channels and upgrade minemeld
  hosts: all
  user: ubuntu
  gather_facts: no
  tasks:
    - name: check minemeld status
      shell: mm-supervisorctl status | grep RUNNING | wc -l
      delay: 10
      retries: 6
      register: result
      until: result.stdout == "4"
      become: true
      become_user: minemeld
    - name: stable minemeld deb version
      shell: dpkg -s minemeld | grep ^Version | awk '{ print $2; }'
      register: stable_minemeld_version
    - name: stable minemeld engine version
      shell: basename $(readlink /opt/minemeld/engine/current)
      register: stable_minemeld_engine_version
    - name: stable minemeld webui version
      shell: basename $(readlink /opt/minemeld/www/current)
      register: stable_minemeld_webui_version
    - name: stable minemeld prototypes version
      shell: basename $(readlink /opt/minemeld/prototypes/current)
      register: stable_minemeld_prototypes_version
    - name: check minemeld API
      uri:
        url: https://127.0.0.1/status/minemeld
        validate_certs: no
        user: admin
        password: minemeld
        force_basic_auth: yes
        return_content: yes
      register: status
    - debug:
        msg: '{{ status }}'
    - name: check nodes
      assert:
        that:
          - 'item.state == 5'
          - 'item.sub_state is not defined or item.sub_state != "ERROR"'
      with_items: '{{ status.json.result }}'
    - name: add unstable repo
      apt_repository:
        repo: deb http://minemeld-updates.panw.io/ubuntu trusty-minemeld-unstable main
        state: present
      become: true
    - name: change minemeld updates config to include beta channel
      copy:
        dest: /etc/minemeld-auto-update.conf
        content: |
          {
            "minemeld-updates": {
              "baseurl": "http://minemeld-updates.panw.io/stage2",
              "channel": ["0_9", "beta0_9"]
            }
          }
        mode: 0644
        group: root
        owner: root
      become: true
    - name: upgrade minemeld
      shell: /usr/sbin/minemeld-auto-update
      become: true

    - name: check minemeld status
      shell: mm-supervisorctl status | grep RUNNING | wc -l
      delay: 10
      retries: 6
      register: result
      until: result.stdout == "4"
      become: true
      become_user: minemeld
    - name: new minemeld deb version
      shell: dpkg -s minemeld | grep ^Version | awk '{ print $2; }'
      register: new_minemeld_version
    - name: new minemeld engine version
      shell: basename $(readlink /opt/minemeld/engine/current)
      register: new_minemeld_engine_version
    - name: new minemeld webui version
      shell: basename $(readlink /opt/minemeld/www/current)
      register: new_minemeld_webui_version
    - name: new minemeld prototypes version
      shell: basename $(readlink /opt/minemeld/prototypes/current)
      register: new_minemeld_prototypes_version
    - name: check minemeld deb upgrade
      assert:
        that:
          - >
            (stable_minemeld_version.stdout != new_minemeld_version.stdout) or
            (stable_minemeld_engine_version.stdout != new_minemeld_engine_version.stdout) or
            (stable_minemeld_webui_version.stdout != new_minemeld_webui_version.stdout) or
            (stable_minemeld_prototypes_version.stdout != new_minemeld_prototypes_version.stdout)
      ignore_errors: true

    - name: upgrade minemeld
      shell: /usr/sbin/minemeld-auto-update
      become: true
    - name: check minemeld status
      shell: mm-supervisorctl status | grep RUNNING | wc -l
      delay: 10
      retries: 6
      register: result
      until: result.stdout == "4"
      become: true
      become_user: minemeld
    - name: new2 minemeld deb version
      shell: dpkg -s minemeld | grep ^Version | awk '{ print $2; }'
      register: new2_minemeld_version
    - name: new2 minemeld engine version
      shell: basename $(readlink /opt/minemeld/engine/current)
      register: new2_minemeld_engine_version
    - name: new2 minemeld webui version
      shell: basename $(readlink /opt/minemeld/www/current)
      register: new2_minemeld_webui_version
    - name: new2 minemeld prototypes version
      shell: basename $(readlink /opt/minemeld/prototypes/current)
      register: new2_minemeld_prototypes_version
    - name: check minemeld deb upgrade
      assert:
        that:
          - new2_minemeld_version.stdout == new_minemeld_version.stdout
          - new2_minemeld_engine_version.stdout == new_minemeld_engine_version.stdout
          - new2_minemeld_webui_version.stdout == new_minemeld_webui_version.stdout
          - new2_minemeld_prototypes_version.stdout == new_minemeld_prototypes_version.stdout
    - name: check minemeld API
      uri:
        url: https://127.0.0.1/status/minemeld
        validate_certs: no
        user: admin
        password: minemeld
        force_basic_auth: yes
        return_content: yes
      register: status
    - debug:
        msg: '{{ status }}'
    - name: check nodes
      assert:
        that:
          - 'item.state == 5'
          - 'item.sub_state is not defined or item.sub_state != "ERROR"'
      with_items: '{{ status.json.result }}'
