pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                    ansiblePlaybook(playbook: 'tests/cfn-template/test.yml', colorized: true)
                }
            }
        }
    }
    post {
        always {
            wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                ansiblePlaybook(playbook: 'tests/cfn-template/cleanup.yml', colorized: true)
            }        
        }
    }
}