pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                    ansiblePlaybook(playbook: 'tests/upgrade/setup.yml', colorized: true)
                }
            }
        }
        stage('Install') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                    ansiblePlaybook(
                        playbook: 'tests/upgrade/install.yml',
                        inventory: 'tests/upgrade/mm-test-inventory',
                        colorized: true
                    )
                }
            }
        }
        stage('Test') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                    ansiblePlaybook(
                        playbook: 'tests/upgrade/test.yml',
                        inventory: 'tests/upgrade/mm-test-inventory',
                        colorized: true
                    )
                }
            }
        }
    }
    post {
        always {
            wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                ansiblePlaybook(playbook: 'tests/upgrade/cleanup.yml', colorized: true)
            }
        }
    }
}
