- name: setup infrastructure
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars:
    jenkins_client_location: "{{ lookup('env', 'CICT_CLIENT_LOCATION') }}"
    jenkins_aws_key_name: "{{ lookup('env', 'CICT_AWS_KEY_NAME') }}"
    jenkins_aws_region: "{{ lookup('env', 'CICT_AWS_REGION') }}"

  tasks:
    - name: start jenkins CFN template
      cloudformation:
        stack_name: minemeld-ci-jenkins
        state: present
        region: "{{ jenkins_aws_region }}"
        disable_rollback: false
        template: files/jenkins-cfn.json
        template_parameters:
          ClientLocation: '{{ jenkins_client_location }}'
          InstanceKeyName: '{{ jenkins_aws_key_name }}'
          InstanceType: m3.medium
        tags:
          Stack: minemeld
      register: jenkins_cfn
    - debug:
        msg: 'Jenkins host: {{ jenkins_cfn.stack_outputs.JenkinsAddress }}'
    - name: wait for ssh
      wait_for:
        host: "{{ jenkins_cfn.stack_outputs.JenkinsAddress }}"
        port: 22
        delay: 20
        timeout: 320
        state: started
      when: jenkins_cfn.changed
    - name: add jenkins instance to host group
      add_host: hostname={{ jenkins_cfn.stack_outputs.JenkinsAddress }} groups=jenkins

- name: configure jenkins
  hosts: jenkins
  user: ubuntu
  gather_facts: no

  vars:
    jenkins_admin_username: "{{ lookup('env', 'CICT_ADMIN_USERNAME') }}"
    jenkins_admin_password: "{{ lookup('env', 'CICT_ADMIN_PASSWORD') }}"
    jenkins_aws_access_key_id: "{{ lookup('env', 'CICT_AWS_ACCESS_KEY_ID') }}"
    jenkins_aws_secret_access_key: "{{ lookup('env', 'CICT_AWS_SECRET_ACCESS_KEY') }}"
    slave_private_ssh_key: "{{ lookup('env', 'SLAVE_SSH_PRIVATE_KEY_FILE') }}"
    slave_aws_region: "{{ lookup('env', 'SLAVE_AWS_REGION') }}"
    slave_aws_key_name: "{{ lookup('env', 'SLAVE_AWS_KEY_NAME') }}"

  tasks:
    - name: waiting for cloud-init
      shell: find /var/lib/cloud/instances -name boot-finished | grep -q -E ".*"
      delay: 30
      retries: 20
      register: result
      until: result | success
    - name: disable wizard
      lineinfile:
        dest: /etc/default/jenkins
        insertafter: JAVA_ARGS=
        regexp: '^JAVA_ARGS=\"\$JAVA_ARGS '
        line: 'JAVA_ARGS="$JAVA_ARGS -Djenkins.install.runSetupWizard=false"'
        state: present
      become: true
    - name: create custom init scripts directory.
      file:
        path: "/var/lib/jenkins/init.groovy.d"
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0775
      become: true
    - name: configure default users
      template:
        src: basic-security.groovy
        dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
        owner: jenkins
        group: jenkins
        mode: 0775
      become: true
    - name: restart jenkins
      service: name=jenkins state=restarted
      become: true
    - name: wait for jenkins
      uri:
        url: http://localhost:8080
        status_code: 403
        timeout: 5
      register: jenkins_service_status
      retries: 60
      delay: 5
      until: >
         'status' in jenkins_service_status and
         jenkins_service_status['status'] == 403
    - name: install Jenkins plugins using password
      jenkins_plugin:
        name: "{{ item }}"
        jenkins_home: /var/lib/jenkins
        params:
          url_username: "{{ jenkins_admin_username }}"
          url_password: "{{ jenkins_admin_password }}"
      with_items:
        - dashboard-view
        - cloudbees-folder
        - timestamper
        - ws-cleanup
        - junit
        - workflow-aggregator
        - github-branch-source
        - pipeline-github-lib
        - pipeline-stage-view
        - git
        - github
        - email-ext
        - mailer
        - ansible
        - envinject
        - ansicolor
    - name: restart jenkins
      service: name=jenkins state=restarted
      become: true

    - name: copy ansible config
      copy:
        src: ansible.cfg
        dest: /var/lib/jenkins/.ansible.cfg
        owner: jenkins
        group: jenkins
      become: true
    - name: ssh key directory
      file:
        path: /var/lib/jenkins/ssh
        state: directory
        owner: jenkins
        group: jenkins
      become: true
    - name: ssh key for ansible AWS slaves
      copy:
        src: '{{ slave_private_ssh_key }}'
        dest: /var/lib/jenkins/ssh/aws.pem
        owner: jenkins
        group: jenkins
        mode: 0600
      become: true
    - name: aws credentials directory
      file:
        path: /var/lib/jenkins/.aws
        state: directory
        owner: jenkins
        group: jenkins
      become: true
    - name: aws credentials
      template:
        src: aws-credentials
        dest: /var/lib/jenkins/.aws/credentials
        owner: jenkins
        group: jenkins
        mode: 0600
      become: true

    - name: setup jenkins upgrade test job
      jenkins_job:
        config: "{{ lookup('template', 'templates/job-upgrade.xml') }}"
        name: MineMeld-Upgrade-Test
        url: http://localhost:8080
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
    - name: setup jenkins minemeld cfn test job
      jenkins_job:
        config: "{{ lookup('template', 'templates/job-cfn-test.xml') }}"
        name: MineMeld-CFN-Test
        url: http://localhost:8080
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
